CREATE TABLE Users
(
  Email VARCHAR(255) NOT NULL,
  Username VARCHAR(255) NOT NULL UNIQUE,
  UserPassword VARCHAR(255) NOT NULL,
  PRIMARY KEY (Email)
);

CREATE TABLE Review
(
  ReviewID INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(255) NOT NULL UNIQUE,
  ReviewText VARCHAR(500) NOT NULL,
  StarRating INT NOT NULL,
  Email VARCHAR(255) NOT NULL, 
  PRIMARY KEY (ReviewID),
  FOREIGN KEY (Email) REFERENCES Users(Email)
);

CREATE TABLE Guitar
(
  GuitarID INT NOT NULL AUTO_INCREMENT,
  Make VARCHAR(255) NOT NULL,
  BrandName VARCHAR(255) NOT NULL,
  Cost NUMERIC(9,2),
  YearMade INT,
  ReviewID INT NOT NULL,
  ExtraDescription VARCHAR(500),
  PRIMARY KEY (GuitarID),
  FOREIGN KEY (ReviewID) REFERENCES Review(ReviewID)
);



CREATE TABLE Accessory
(
  AccessoryID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Type VARCHAR(255) NOT NULL,
  Cost NUMERIC(9,2),
  BrandName VARCHAR(255) NOT NULL,
  ReviewID INT NOT NULL,
  PRIMARY KEY (AccessoryID),
  FOREIGN KEY (ReviewID) REFERENCES Review(ReviewID)
);

